### PR TITLE
Paina Liubov

### PR DESCRIPTION
**Pull request by lubba**

### CODE REVIEW

**Comment by lubba** [comment]
I've lost my IDE right now. The only thing I wanted to change is TagTable.TABLE_NAME = "tags", not "tag"

**Comment by thevery** [comment]
crash on adding tag:

```
FATAL EXCEPTION: main
Process: com.csc.colloquium2, PID: 30629
java.lang.IllegalArgumentException: The key must be an application-specific resource id.
at android.view.View.setTag(View.java:19920)
at com.csc.lpaina.colloquium2.EditActivity.onClick(EditActivity.java:115)
```

**Comment by thevery** [comment]
task list seems to be broken, too (same tasks on return from edit)

**Comment by thevery** [comment]
0

**Pull request closed without merging**
